name: suyo_prototype
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  intl: ^0.18.1
  flutter_animate: ^4.2.0
  shared_preferences: 2.5.3
  animations: 2.0.11
  connectivity_plus: ^6.1.4

  # Location & Permissions
  google_maps_flutter: ^2.6.1
  geolocator: ^10.1.0
  permission_handler: ^11.3.1

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_style.json
